name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_call:
    inputs:
      uploadJar:
        description: 'Whether or not to upload a release jar to GitHub'
        type: boolean
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode verify
      - if: ${{ inputs.uploadJar }}
        name: Upload jar if needed
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: target/apple-notes-liberator*.jar

